# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Zero_One
tagline:             'Cpp世界中探寻'
description:         '抽屉式的博客边框.'
url:                 
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              吴杭沉
  url:               
  email:             1714593434@Outlook.com

# Custom vars
version:             1.0.0
